<!DOCTYPE HTML>
<html>
<head>
<meta charset = "utf 8">

<!--This section is for CSS-->
<style>

body
{background-color : black ; 
font-family:"Helvetica";

} 
#Main-title 

{background-color:green; font-family:"Lucida Sans"; 
}

#Beautiful-but-torn {color:chartreuse;}

h4 

{color: brown; font-family:"Helvetica";}

h3 

{color:brown; font-family:"Helvetica";}

ol

{color:burlywood; }

.poem-text 

{color: white; font-family:"Helvetica";}

#image-with-external-url

{color:bisque; font-family:"Helvetica";}

tbody

{color:white;font-family:"Helvetica";}

</style>

<title> Writing a poem with HTML </title>
</head>

<body>
<h1 id = "Main-title"> Camouflaged </h1> 
<h4> A short poem about the beauty of being broken </h4> 

<li><a href="#favorite-poets">Go down to Favorite Poets</a></li>

<!--This is the body of the poem-->

<p class ="poem-text">In all chaotic beauty lies a wounded work of art.
<em>Beautiful but torn,</em> wreaking havoc on my heart. <br>
Camouflaged by insecurities, blinded by it all. <br>
<strong>I love the way you sit there and barely notice me at all.</strong> 

</p>

<p class ="poem-text">Life and death; without one there cannot be the other.<br>
    For some, it's short, but they live it like no other.<br>
    For most, it's long, and to be happy they don't ever bother.<br>
    Life cannot be lived without the love of others.</p>

<p class ="poem-text"> The second we are born is the second we begin to die.<br>
    As a child, we live life and don't worry why.<br>
    As we grow, it gets tougher and we don't want to try.<br>
    Like everything else, it will end and we'll have to say goodbye. </p>

<h3 id=favorite-poets> Favorite poets</h3>

<li><a href="#Main-title">Go back to Main Title</a></li>

<!--This is for the links-->

<ol>
    <li> <a target ="_blank" href = "https://en.wikipedia.org/wiki/Gabriel_Garc%C3%ADa_M%C3%A1rquez">Gabriel Garcia Marquez</a></li>

<img src = "https://tse2.mm.bing.net/th?id=OIP.TeBfFyn4V8ixIUV_RjO2qQHaGL&pid=Api&P=0&w=196&h=164" alt = "gabriel garcia marquez" width = "150">

    <li><a target = "_blank" href = "http://www.harukimurakami.com/">Haruki Murakami</a></li>

    <img src = "https://s26162.pcdn.co/wp-content/uploads/2019/05/Haruki-Murakami-credit-Elena-Seibert-1240x823.jpg" alt ="haruki murakami" width = "150">
    
    <li><a target = "_blank" href = "https://www.britannica.com/biography/Pablo-Neruda">Pablo Neruda</a></li>

    <img src = "https://tse2.mm.bing.net/th?id=OIP.-lc5n_659ZaaK2gO7lcDCAHaE6&pid=Api&P=0&w=234&h=156" alt = "pablo neruda" width = "150"> <br>

    <br>

</ol>

<a target="_blank" href="https://www.thoughtco.com/what-is-poetry-852737">Read more about Poetry</a>

<p id ="image-with-external-url">Image with External URL</p>

<a target ="_blank" href="https://en.wikipedia.org/wiki/Poetry"></a>

<a target="_blank" href = "https://tse3.mm.bing.net/th?id=OIP.-Zi6gfLaLo45K59bREEboQHaE7&pid=Api&P=0&w=258&h=173"><img src ="https://www.readinghouse.com/images/easyblog_articles/22/poetry-word_20160321-201054_1.jpg" width ="300"></a>

<table>
<thead>
<th>Author</th>
<th>Works</th>
</thead>

<tbody>
    <tr>
    <td>Gabriel Garcia Marquez</td>
    <td>One Hundred Years of Solitude</td>
</tr>

<tr>
    <td>Haruki Murakami</td>
    <td>1Q84</td>
</tr>

<tr>
    <td>Pablo Neruda</td>
    <td>Selva Austral</td>
</tr>

</tbody>

</table>

</body>

</html> # Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run